name: ci

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.vscode/**'
    branches:
      - 'main'
  workflow_dispatch: null

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      -
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      -
        name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ha-lambda-tailscale
          IMAGE_TAG: latest
          TAILSCALE_VERSION: 1.78.1
          PYTHON_VERSION: 3.13
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg TAILSCALE_VERSION=$TAILSCALE_VERSION --build-arg PYTHON_VERSION=$PYTHON_VERSION .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
